### ISSUE TITLE
Feature Request: scrollable container when panel exceeds page width

### ISSUE THREAD

**Issue by punk-t** [GreenItSolutions/dokuwiki-plugin-switchpanel#13]
Hello!

Switch panels, that exceeds the display width, are not scrollable by now. The former patch panels are. This is useful for large switches like:
```
<switchpanel logo=none case="rj45">
==line:number=28
  1:
  25:case=none
  26:case=none
  27:case=none
  28:case=none
==line
  1:
  24,Uplink,48:color=#ffffff,text=Alle VLANs; tagged
  25:case=2of
  26:case=2of
  27:case=2of
  28:case=2of
</switchpanel>
```
The code above is a real life example of a Dell PowerConnect2848 Switch.

Comparing the two generated html outputs of patch panel versus switch panel, I found an explicit width/height information at the surrounding `div` container in patch panel.

Maybe its just so simple.

**Comment by GreenItSolutions** [comment]
Thanks
