### ISSUE TITLE
Feature request: LabelColor and/or LabelBgColor

### ISSUE THREAD

**Issue by punk-t** [GreenItSolutions/dokuwiki-plugin-switchpanel#15]
In my company I deal very intensive with tagged and untagged VLANs. In addition to the possibility of coloring the cases, it might be useful to color the label of a case or its background.

When one uses different case colors for different VLANs there is no fast and visually significant posibility to mark some port as a port of special interest.

As an example:

```
<switchpanel case=rj45>
==text:size=12
==line:number=8
  1
  2
  3,label:labelBgColor=#ff0000,title:text=brief explantaion
</switchpanel>
```

Might be cool, maybe :)

Greetings

**Comment by gLUK00** [comment]
Hello,

Do you have a picture to illustrate the desired result ?

Greetings
