### ISSUE TITLE
Popup messages don't work after upgrade

### ISSUE THREAD

**Issue by itorralba** [GreenItSolutions/dokuwiki-plugin-switchpanel#16]
Popup messages don't work after upgrade to the last version of the switch panel plugin.
We tested with Firefox and Chrome.
There have been no changes in versions of Dokuwiki, Apache or PHP.
Is it necessary to make any changes to the server?
Many thanks

**Comment by GreenItSolutions** [comment]
Hello,
What is the error message ?
Cordially

**Comment by itorralba** [comment]
Hello.
There are no errors in apache log files.
I've tried with a second server, upgrading switch panel plugin to the last version.
After upgrading, when mouse pointer is over a switch port with "text" property, no longer appears pop-up window with label and text or link.
Nobody else has this problem ?
May be a server configuration ? It is a dedicated Dokuwiki server.
Thanks
Regards

**Comment by itorralba** [comment]
Hello.
In both servers, after restoring only the directory "dokuwiki/lib/plugins/switchpanel" from previous version, from backup, pop up messages works again.
Thanks again.
Regards

**Comment by punk-t** [comment]
Hi there,

I found the problem concerning this issue. There is a JS error in the actual script.js-file. The two properties `showToolTip` and `hideToolTip` are gone in the script file but are still called at every `onMouseOver`- or `onMouseOut`-event.
In fact the whole script.js and style.css looks completely different. I looked around and found an older patchpanel-version with exactly that code. 
Maybe you accidently mixed up that two plugin versions and merged them?
Restoring these two files let the tooltips go alive again :)

**Comment by itorralba** [comment]
Hi !
Patchpanel plugin and Switchpanel plugin were on the server simultaneously, but Patchpanel was disabled.
At this time, only Switchpanel plugin is installed on Dokuwiki.
How to proceed for the update to work?
I tried again and still not working

Thanks again
Iñaki

(Sorry for my poor English)

**Comment by GreenItSolutions** [comment]
Good evening,
there was actually a carry-code error between switchpannel and patchpanel.
I corrected the JS and CSS files and updated dates in the Wiki.

Can you confirm the correction?

Thanks
Regards

**Comment by itorralba** [comment]
Good night !
It works !
Great job with this plugin and your support.
Many thanks.
Regards
