### ISSUE TITLE
Feature requests: alternative name for links

### ISSUE THREAD

**Issue by Django-BOfH** [GreenItSolutions/dokuwiki-plugin-switchpanel#19]
It were great, if I could give alternative names for links (mouse-over) instead of showing the whole URL.

**Comment by GreenItSolutions** [comment]
Hello,

It's ok, use "textlink" tag.

Greetings

**Comment by Django-BOfH** [comment]
Oh, O.K., now it looks like I expected! Thanx 4 help!
![switchpanelplugin_01](https://cloud.githubusercontent.com/assets/6991904/20516359/82a9447e-b096-11e6-9d6b-ff9c91193cfd.png)
