### ISSUE TITLE
Label text for different case types

### ISSUE THREAD

**Issue by punk-t** [GreenItSolutions/dokuwiki-plugin-switchpanel#2]
Hello!

First of all: THANK YOU VERY MUCH, I was looking for an extended patch panel plugin like this. I forked the [patch panel plugin] (https://github.com/grantemsley/dokuwiki-plugin-patchpanel) and tried by my own, but your results are much better.

Now the technical part:
I played with something like
```
<switchpanel logo=none>
==text
ip-adresse
==line
1,1:color=#FF6164,case=rj45,text="Ein Text-Test"
2,2:color=#FF6164,case=of,text="Ein Text-Test"
3,3:color=#FF6164,case=2of,text="Ein Text-Test"
4,4:color=#FF6164,case=gbic,text="Ein Text-Test"
5,5:color=#FF6164,case=serial,text="Ein Text-Test"
6,6:color=#FF6164,case=close,text="Ein Text-Test"
</switchpanel>
```
and hoped to get a popup for every case type but the result of example above is: No popup for of, 2of,gbic,none. At least for types of, 2of and gbic an additional text is vitally useful. 

Can you confirm this as an issue or did I do something stupid?

Greetings 
Punkt

**Comment by GreenItSolutions** [comment]
Hello,

Thanks for your feedback.

There was a bug on displaying popup.

I fixed it :)

Regards
