### ISSUE TITLE
Bug: "Popup message information and link"

### ISSUE THREAD

**Issue by Django-BOfH** [GreenItSolutions/dokuwiki-plugin-switchpanel#20]
I'm using "popup message information and link". Those small windows are shown from actual cursor position "upper left corner".
If one of the rightest ports on my displayed 48 Port Switch, I can't see the whole content, 'cause most of the informations are "behind" the right site of my monitor:
![switchpanelbug](https://cloud.githubusercontent.com/assets/6991904/20304528/00f5fbc6-ab31-11e6-9fd7-6d42d6763384.png)

**Comment by GreenItSolutions** [comment]
Hello,

I have solved the problem using javascript.
Can you update your version of the plugin ?

Greetings

**Comment by Django-BOfH** [comment]
Thanx 4 help, the new version is working as expected!
![switchpanelplugin_01](https://cloud.githubusercontent.com/assets/6991904/20516435/d4371992-b096-11e6-995d-b812b79e32e2.png)
