### ISSUE TITLE
Default logo link should be no link

### ISSUE THREAD

**Issue by FosseWay** [GreenItSolutions/dokuwiki-plugin-switchpanel#21]
Currently, if no logo for logoLink is specified, the plugin defaults to http://www.greenitsolutions.fr/

I completely understand why you would want to do that as a plugin author. However, my wiki is running in a corporate environment, so this default behaviour is not deisrable. I can't force users to specify `logo`, but management will not be pleased to see links to external sites which have nothing to do with our company. For now, I had to hack the plugin, but perhaps you would consider changing the default behaviour...?

Thank you for your work on this useful plugin!

**Comment by GreenItSolutions** [comment]
Hello,

If you want to change the default behavior of the plugin directly from the code, I recommend the following change :

$opt = array(
	'logo'=>'none',
	//'logo'=>DOKU_BASE.'lib/plugins/switchpanel/images/greenIt.svg',

By

**Comment by FosseWay** [comment]
Thank you for your useful reply. That's what I have already done (see previous post where I hacked my installed version of the plugin).

Only problem - and I admit it's only a problem for me - is that I'll have to re-hack it each time I update to a newer version of dokuwiki-plugin-switchpanel. It's always nice to avoid manual-hack workarounds if possible. If I submitted a which included an optional config item to override this value, would you consider it?
