### ISSUE TITLE
If text="" specified, display broken unless case type also specified

### ISSUE THREAD

**Issue by FosseWay** [GreenItSolutions/dokuwiki-plugin-switchpanel#22]
Adding a `text`, `link`, or `textlink` value to a port causes unexpected display issues, unless case type is specified for that port. This makes case type defaulting not very useful.

This code:
````
<switchpanel>
==line:number=6
1,1,
2,2
3,3
4,4
5,5
6,6
</switchpanel>
````

displays:
![image](https://user-images.githubusercontent.com/26946862/26890236-dde5dd7e-4b7e-11e7-9c28-995fd21bb6ec.png)
which is what I expect.

However, I want to add a hover label to the port. I try this code:
````
<switchpanel>
==line:number=6
1,1,text="example"
2,2
3,3
4,4
5,5
6,6
</switchpanel>
````
but this appears to pass the whole `text="example"` tag through, which is surely not desirable:
![image](https://user-images.githubusercontent.com/26946862/26889944-caf4758c-4b7d-11e7-9bb9-683af0cc11f3.png)

I can work around that by specifying the case type:
````
<switchpanel logo="http://www.opensecurityarchitecture.org/cms/images/OSA_images/icon_library/osa_hub.png">
==line:number=6
1,1:case=rj45,text="example"
2,2
3,3
4,4
5,5
6,6
</switchpanel>
````
which then gives me what I expect:
![image](https://user-images.githubusercontent.com/26946862/26890196-b851ac5a-4b7e-11e7-8fca-1060111a785e.png)

Am I doing something wrong, or is the case type defaulting broken when `text` is specified?

**Comment by GreenItSolutions** [comment]
Hello,

The syntax is no correct  :
1,1,text="example"

Use this :
1,1,example

What should be remembered is that at the beginning of the line the separator "," uses the third argument as the text of the element. The separator ":" defines the options of the line.

==line:number=(number of cases),color=(backgroud color),case=(type of case),labelLeft=(label left),labelRight=(label right),colorLabelLeft=(color of label left),colorLabelRight=(color of label right)
1,label,title:color=(backgroud color),text=(text of popup message),link=(url of link),case=(type of case),target=(type of link target)

By
