### ISSUE TITLE
Documenting Server Racks

### ISSUE THREAD

**Issue by Paebbels** [GreenItSolutions/dokuwiki-plugin-switchpanel#27]
I like your DokuWiki plugin very much. Is it possible to create a derived plugin to document Racks?

The existing [rack plugin](https://www.dokuwiki.org/plugin:rack) is outdated and doesn't look as nice as your plugin.

**Comment by Support-Green-IT-Solutions** [comment]
Racks plugin must be redevelop from scratch.
It's not possible for us.
Thanks for your interest.
