### ISSUE TITLE
PHP7 compliance

### ISSUE THREAD

**Issue by blacklord049** [GreenItSolutions/dokuwiki-plugin-switchpanel#5]
Hi,

Seems that the plugin is not PHP7 compliant.
Ex : Warning: Declaration of syntax_plugin_switchpanel::render($mode, &$renderer, $opt) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in C:\xampp\htdocs\wiki\lib\plugins\switchpanel\syntax.php on line 432

Thank you

**Comment by arnaud-sk** [comment]
I have same problem with php7 : 

> **Warning**: Declaration of action_plugin_switchpanel::register(&$controller) should be compatible with DokuWiki_Action_Plugin::register(Doku_Event_Handler $controller) in \xampp\htdocs\lib\plugins\**switchpanel\action.php on line 208**

> **Warning**: Declaration of syntax_plugin_switchpanel::render($mode, &$renderer, $opt) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in \xampp\htdocs\lib\plugins\**switchpanel\syntax.php on line 466**

**Comment by LarsGit223** [comment]
PRs #3 and #23 would fix this problem.
