### ISSUE TITLE
I am depreciating my version in favor of this

### ISSUE THREAD

**Issue by grantemsley** [GreenItSolutions/dokuwiki-plugin-switchpanel#8]
You have done a great job carrying on from my [patchpanel plugin](https://github.com/grantemsley/dokuwiki-plugin-patchpanel).

Obviously, I haven't had time to maintain my version in quite some time, so I am going to switch to using your version, and depreciate my own with links to this project.

One thing I would appreciate, since this is a fork of my project, is if you gave me credit somewhere in the source, as I did with the rack plugin that I originally based mine on.

**Comment by gLUK00** [comment]
Of course,

I added the source reference of your project :)

https://github.com/GreenItSolutions/dokuwiki-plugin-switchpanel/blob/master/syntax.php

I Thank You for your work

By
